/**
 * Brief assembly — Phase 5 Chunk 4. Per PLAN/SKILL_CREATOR.md §7.
 *
 * The brief is the JSON payload we send as the user message to a headless
 * skill-creator invocation. It's mostly the Planner's accepted proposal
 * verbatim — skill-creator's job is to author the SKILL.md package
 * matching the brief, not to re-reason about the user's environment.
 *
 * Cap: ≤60 KB total. Truncation priority:
 *   1. webResearch.recentInnovations
 *   2. integration citations
 *   3. webResearch.bestPracticePatterns sources
 *   4. userNarrativeEdits (last — user authorship is precious)
 */
import type { ActionItem, ConversationSummary } from '../../storage/types.js';
import type { ResolvedSkillCapabilityProfile } from './planner-review.js';

const MAX_BRIEF_BYTES = 60 * 1024;

export interface InstallTarget {
  scope: 'project' | 'user';
  path: string;
  skillName: string;
}

export interface SkillCreatorBrief {
  action: {
    id: string;
    title: string;
    description: string;
    priority: string;
    linkedDiscussion?: { id: string; summary: ConversationSummary };
  };
  skillPlannerProposal: ResolvedSkillCapabilityProfile['proposal'];
  capabilityProfile: {
    grantedTools: string[];
    acceptedTier: ResolvedSkillCapabilityProfile['acceptedTier'];
    acceptedIntegrationIds: string[];
    acceptedStakeholderNames: string[];
    userNarrativeEdits?: string;
    detectedEnvironment: {
      platform: string;
      mcpServers: string[];
      cliTools: string[];
      envVars: string[];
      chrome: boolean;
      computerUseAvailable: boolean;
    };
  };
  installTarget: InstallTarget;
  constraints: typeof DEFAULT_CONSTRAINTS;
}

export const DEFAULT_CONSTRAINTS = {
  frontmatter: 'Claude Code spec; see when_to_use, allowed-tools, model, etc.',
  bodyMustExecute:
    'Encode the proposed workflow as ordered, executable steps using ONLY the tools in allowed-tools. ' +
    'Do not produce a how-to guide — produce an execution system prompt.',
  invocationHintsAreLoadBearing:
    'For EACH integration in skillPlannerProposal.integrations[], the emitted SKILL.md body MUST include the literal ' +
    'invocationHint.snippet inside a code block. You MAY surround the snippet with context, validation logic, and ' +
    'follow-up steps — but you MUST NOT paraphrase, abbreviate, or rewrite the snippet. The snippet is the contract.',
  fallbacks: 'For each integration with fallbackIfMissing set, emit explicit fallback behavior in the body.',
  stakeholderHandoffs:
    'For each stakeholderTouchpoint where produces=artifact, write the artifact to artifactPath using ' +
    'artifactTemplate verbatim (leave bracketed placeholders unresolved if unknowable at build time). ' +
    'For produces=send, use sendVia exactly as the mcp tool entry.',
  bodySize: '≤500 lines for SKILL.md; everything else in references/ or scripts/.',
  vetoesAreMandatory:
    'For each entry in skillPlannerProposal.vetoes[], emit a MUST NOT line in the SKILL.md body matching the veto exactly.',
  provenanceFooter:
    'Append: > Generated by aab actions solve from action <short-id>; planner tier <tier>; <N> integrations.',
};

export interface BuildBriefOptions {
  action: ActionItem;
  capabilityProfile: ResolvedSkillCapabilityProfile;
  installTarget: InstallTarget;
  discussionSummary?: ConversationSummary;
}

export function buildSkillCreatorBrief(opts: BuildBriefOptions): {
  brief: SkillCreatorBrief;
  bytes: number;
  truncated: string[];
} {
  const cp = opts.capabilityProfile;
  const truncated: string[] = [];

  const brief: SkillCreatorBrief = {
    action: {
      id: opts.action.id,
      title: opts.action.title,
      description: opts.action.description,
      priority: opts.action.priority,
      ...(opts.action.discussionId && opts.discussionSummary
        ? { linkedDiscussion: { id: opts.action.discussionId, summary: opts.discussionSummary } }
        : {}),
    },
    skillPlannerProposal: cp.proposal,
    capabilityProfile: {
      grantedTools: cp.grantedTools,
      acceptedTier: cp.acceptedTier,
      acceptedIntegrationIds: cp.acceptedIntegrationIds,
      acceptedStakeholderNames: cp.acceptedStakeholderNames,
      userNarrativeEdits: cp.userNarrativeEdits,
      detectedEnvironment: {
        platform: cp.recon.pc.platform,
        mcpServers: cp.recon.pc.mcpServers.map((m) => m.name),
        cliTools: cp.recon.pc.cliTools.map((t) => t.name),
        envVars: cp.recon.pc.envVars,
        chrome: cp.recon.pc.chrome,
        computerUseAvailable: cp.recon.pc.computerUseAvailable,
      },
    },
    installTarget: opts.installTarget,
    constraints: DEFAULT_CONSTRAINTS,
  };

  let bytes = Buffer.byteLength(JSON.stringify(brief), 'utf8');
  // Truncation priority order (T see §7).
  if (bytes > MAX_BRIEF_BYTES) {
    // 1. drop recentInnovations
    // (cast intentionally — we're mutating a structural type)
    (brief as unknown as { skillPlannerProposal: { recentInnovations?: unknown[] } }).skillPlannerProposal.recentInnovations = [];
    bytes = Buffer.byteLength(JSON.stringify(brief), 'utf8');
    truncated.push('webResearch.recentInnovations');
  }
  if (bytes > MAX_BRIEF_BYTES) {
    // 2. drop per-integration citations
    for (const i of brief.skillPlannerProposal.integrations) {
      (i as unknown as { citations?: unknown[] }).citations = [];
    }
    bytes = Buffer.byteLength(JSON.stringify(brief), 'utf8');
    truncated.push('integration.citations');
  }
  if (bytes > MAX_BRIEF_BYTES && brief.capabilityProfile.userNarrativeEdits) {
    // 3. last resort — drop narrative edits
    brief.capabilityProfile.userNarrativeEdits = brief.capabilityProfile.userNarrativeEdits.slice(0, 800) + '…';
    bytes = Buffer.byteLength(JSON.stringify(brief), 'utf8');
    truncated.push('userNarrativeEdits (last 200 chars+ dropped)');
  }
  return { brief, bytes, truncated };
}

/**
 * Render the brief into the wire-shape user message that goes to the
 * `claude -p` call (skill-creator system prompt is added via
 * --append-system-prompt-file). Includes the "print SKILL_CREATOR_DONE
 * when finished" sentinel so we can robustly detect completion in
 * `--output-format stream-json` output.
 */
export function renderUserMessage(brief: SkillCreatorBrief): string {
  return [
    'Author a Claude Code skill matching this brief. Write all files into the current working directory.',
    '',
    'Required output: an installable skill package with SKILL.md at the root + any supporting files',
    `under references/ or scripts/. The skill name MUST be "${brief.installTarget.skillName}".`,
    '',
    'When done, print a single line on its own: SKILL_CREATOR_DONE: ' + brief.installTarget.skillName,
    '',
    'Brief:',
    '```json',
    JSON.stringify(brief, null, 2),
    '```',
  ].join('\n');
}
